apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "caluma.fullname" . }}-emeis
  labels:
{{ include "caluma.labels" . | indent 4 }}
    app.kubernetes.io/component: emeis
  annotations:
    checksum/emeis-secret: {{ include (print $.Template.BasePath "/emeis-secret.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "caluma.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: emeis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "caluma.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: emeis
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.emeis.repository }}:{{ if .Values.image.emeis.tag }}{{ .Values.image.emeis.tag }}{{ else }}{{ .Chart.AppVersion }}{{ end }}"
          imagePullPolicy: {{ .Values.image.emeis.pullPolicy }}
          env:
            - name: DATABASE_HOST
              {{- if and .Values.postgresql.enabled .Values.emeis.postgresql.existingHost }}
              {{ fail "postgresql.enabled and emeis.postgresql.existingHost are mutually exclusive, please pick one" }}
              {{- end }}
              {{- if .Values.postgresql.enabled }}
              value: "{{ template "caluma.fullname" . }}-postgresql"
              {{- else if .Values.emeis.postgresql.existingHost }}
              value: {{ .Values.emeis.postgresql.existingHost | quote }}
              {{- else }}
              {{ fail "neither postgresql.enabled or emeis.postgresql.existingHost are set, please pick one" }}
              {{- end }}
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: "{{ .Values.postgresql.global.postgresql.auth.emeis.username }}"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ template "caluma.fullname" . }}-postgresql-emeis"
                  key: password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.existingSecret }}
                  name: {{ .Values.existingSecret | quote }}
                  {{- else }}
                  name: "{{ template "caluma.fullname" . }}-emeis"
                  {{- end }}
                  key: secretkey
            - name: ALLOWED_HOSTS
              value: "{{ .Values.allowedHosts }}"
            - name: VISIBILITY_CLASSES
              value: "caluma.caluma_core.visibilities.Any"
            - name: PERMISSION_CLASSES
              value: "caluma.caluma_core.permissions.AllowAny"
{{- if .Values.emeis.additionalEnvironment }}
{{ toYaml .Values.emeis.additionalEnvironment | indent 12 }}
{{- end }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            # TODO: define better livenessProbe
            tcpSocket:
              port: http
          readinessProbe:
            # TODO: define better readinessProbe
            tcpSocket:
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.image.emeis.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
