name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.10.3

      - name: install helm unittest
        run: |
          helm env
          helm plugin install https://github.com/helm-unittest/helm-unittest

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct --config=hack/chart-testing/ct.yaml list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct --config=hack/chart-testing/ct.yaml lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Setup cluster for chart-testing (install)
        run: hack/deploy/init.sh
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct --config=hack/chart-testing/ct-install.yaml install
